version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Flask app
          command: |
            . venv/bin/activate
            python app.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

